name: prueba_tecnica
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  google_fonts: ^4.0.5
  http: ^1.0.0
  provider: ^6.0.5

flutter:
  uses-material-design: true
  assets:
    - assets/
